### ISSUE TITLE
Aegis doesn't work with subclasses

### ISSUE THREAD

**Issue by caleb** [makandra/aegis#1]
Due to an existing design, I have AR classes that are in a hierarchy. I have a baseclass that `has_roles`, and subclasses that I want to use that.

Right now, Aegis doesn't work with the subclasses because it uses class properties to store the name of the accessor to the role_name column.

The solution I'm using now is to define those class properties (@aegis_role_name_reader & writer) in each subclass.

I have a patch to Aegis that uses Rails' class_inheritable_accessor to allow subclasses to inherit that class property.

The patch is here: http://github.com/caleb/aegis/commit/669f8271364c7bf26bfe15aa63cbc38a81ca0c42

I've also added the appropriate tests by creating a subclass of the User class, and duplicating all tests done on the User test with the "student" role.

Thanks for the useful library

**Comment by triskweline** [comment]
This was fixed by the merge of caleb's fork.
