### ISSUE TITLE
check_permissions helper does not consider inheritance

### ISSUE THREAD

**Issue by bradrobertson** [makandra/aegis#10]
if I use the `permissions` method in my application controller, then want to test that all controllers inheriting from this controller check that permission, I can't use:

check_permissions

on each individual controller.  I would think I should be able to test this controller, rather than just testing the application_controller itself

**Comment by triskweline** [comment]
It should be possible, yes. I'm curious why you are using the same permissions for all your controllers?

**Comment by bradrobertson** [comment]
I have a Rails engine that is an administrative application.  That engine has its own application_controller that all the other controllers within it inherit from.  I've just made an 'admin' action that I check against in this application_controller.  Is there a better way of locking down this whole application to users?

**Comment by triskweline** [comment]
I think your solution is fine.
