### ISSUE TITLE
undefined method `object' for #<LocationsController>

### ISSUE THREAD

**Issue by brett-richardson** [makandra/aegis#11]
Whenever I try to edit a resource with Aegis-managed resource permissions I get the following:
undefined method `object' for #LocationsController:0xa6baa94

My Permissions model contains the following:
    resources :locations do
        action :index, :show do
            allow :everyone
        end

```
    action :search, :collection => true do
        allow :everyone
    end

    action :create do
        allow :location_owner
    end

    action :edit, :update, :destroy do
        allow :location_owner do
            user.locations.include? object
        end
    end
end
```

And my controller is pretty standard as well:
    # Authorizations
    include Aegis::Controller
    permissions :locations

I'm probably doing something very basic wrong here, but I've looked into the Aegis::Controller class and can't figure out what's happening here.

Any help would be greatly appreciated... cheers.

**Comment by triskweline** [comment]
Your controller needs to define a method that returns the current member object. That method is assumed to be #object by default.

See the example under "Integrating permission resources with RESTful controllers" here: https://github.com/makandra/aegis/wiki/Controller-integration
