### ISSUE TITLE
ActiveRecord::Errors.default_error_messages has been deprecated

### ISSUE THREAD

**Issue by jakewendt** [makandra/aegis#2]
I added "validates_role_name" to my user model and saw this output from my tests.  

DEPRECATION WARNING: ActiveRecord::Errors.default_error_messages has been deprecated. Please use I18n.translate('activerecord.errors.messages').. (called from default_error_messages at /Library/Ruby/Gems/1.8/gems/activerecord-2.3.4/lib/active_record/validations.rb:131)

I replaced "ActiveRecord::Errors.default_error_messages[:inclusion]" with "I18n.translate('activerecord.errors.messages')[:inclusion]" in Aegis::HasRole.validates_role_name and the deprecation warning went away.

**Comment by makandra** [comment]
Thanks for reporting this. The patch is now in the master and the latest gem.
