### ISSUE TITLE
Incompletely matching permissions

### ISSUE THREAD

**Issue by jakewendt** [makandra/aegis#3]
The method_missing_with_aegis_permissions and respond_to_with_aegis_permissions in aegis/has_role and method_missing in aegis/role are incorrectly or incompletely matching permissions that aren't defined permissions.  The RegEx matches are never checked to see if there were ever defined as permissions so User.new.respond_to?("may_do_something?") will always return true, no matter what "do_something" is.

I am proposing something like the following be added to Aegis::Permissions::ClassMethods

```
    def self.permission_names
            @permission_blocks.keys
    end

    def self.exists?(permission)
            Permissions.permission_names.include?(
                    Aegis::Normalization.normalize_permission(permission).to_sym
            )
    end
```

and that the matches have something like the following add to the condition lines to be more correct.

```
    && ::Permission.exists?($1)
```

Yes, I could do this myself on a fork, but I don't really have the time to test and troubleshoot.  Who knows what sort of problems this might cause.  Sorry.

**Comment by triskweline** [comment]
This is the intended behaviour. We like to define roles with default permissions, and only explictely define permissions where they differ from the default.
