### ISSUE TITLE
multiple roles

### ISSUE THREAD

**Issue by LuNiPriSe** [makandra/aegis#4]
I love this gem, but I am thinking of switching to cancan, because it allows multiple roles. I like your syntax better though.

Could somehow fix the gem to look for has_many roles ?

thanks in advance,

Luis

**Comment by makandra** [comment]
Hi Luis,

We believe that you should only distinguish roles that have different ways of resolving their permissions. A typical set of roles would be

```
* anonymous guest (has access to nothing with some exceptions)
* signed up user (has access to some things depending on its attributes and associations)
* administrator (has access to everything)
```

We don’t do multiple, parametrized roles like "leader for project #2" and "author of post #7". That would be reinventing associations. Just use a single :user role and let your permission block query regular associations and attributes.

Many regards
Henning
