### ISSUE TITLE
Actions passed objects not working correctly

### ISSUE THREAD

**Issue by KingOfBrian** [makandra/aegis#6]
```
action :show_object do |deal|
   ....
end
```

deal == Aegis::Parser:0x101091aa8

This is a show stopper for me, not sure how hard a fix it is.   Any thoughts on what's going on?   It looks like 'take_object' might not be set correctly on the action object, but I just briefly checked the code.

Thanks

**Comment by triskweline** [comment]
Would you send me your whole permissions class, then I will take a look.

**Comment by KingOfBrian** [comment]
I sent you a message.

**Comment by triskweline** [comment]
The allow block should take the deal argument, not the action. This has changed with the release of Aegis 2.

The new gem version raises an error if an action block is defined with an argument.

**Comment by KingOfBrian** [comment]
I thought that was what I was doing..  In the example above if I print out deal it is really an Aegis::Parser.

**Comment by triskweline** [comment]
In your example the action-block takes an argument called "deal". This is wrong. The allow or deny block should take the argument.
